# Generated by Django 4.1.4 on 2022-12-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('full_text', models.TextField()),
                ('summary', models.TextField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
